'use client'
import { useEffect, useMemo, useState } from 'react'
import { supabase } from '../lib/supabase'

type Worker={name:string,busyUntil:string|null}
type Order={id:string,created_at:string,shop:string,phone_tail:string,people:number,duration:number,start_time:string,status:string,assigned:string[],base_fee:number,extra_fee:number,tip:number,base_pay_method:string,extra_pay_method:string,tip_pay_method:string}
const defaultWorkers=['Leah','Lily','C','Y']
const baseCommission:Record<number,number>={70:30,90:40,110:50}
function nowTime(){return new Date().toTimeString().slice(0,5)}
function addMin(t:string,m:number){const [h,mi]=t.split(':').map(Number);const d=new Date();d.setHours(h,mi+m,0,0);return d.toTimeString().slice(0,5)}
function calcPay(o:Partial<Order>){const base=baseCommission[o.base_fee||0]??(o.base_fee||0)*0.5;const extra=(o.extra_fee||0)*0.5;const tip=o.tip||0;const cash=(o.base_pay_method==='cash'?base:0)+(o.extra_pay_method==='cash'?extra:0)+(o.tip_pay_method==='cash'?tip:0);const check=(o.base_pay_method==='card'?base:0)+(o.extra_pay_method==='card'?extra:0)+(o.tip_pay_method==='card'?tip:0);return {base,extra,tip,cash,check,total:base+extra+tip}}
export default function Page(){
 const [shop,setShop]=useState('Weatherford'); const [wheel,setWheel]=useState(defaultWorkers); const [orders,setOrders]=useState<Order[]>([]); const [workers,setWorkers]=useState<Worker[]>(defaultWorkers.map(name=>({name,busyUntil:null})))
 const [form,setForm]=useState<any>({phone_tail:'',people:1,duration:60,start_time:nowTime(),base_fee:90,extra_fee:0,tip:0,base_pay_method:'card',extra_pay_method:'cash',tip_pay_method:'cash',specified:''})
 async function load(){const {data}=await supabase.from('orders').select('*').eq('shop',shop).order('created_at',{ascending:false}).limit(100); if(data) setOrders(data as Order[])}
 useEffect(()=>{load(); const ch=supabase.channel('orders').on('postgres_changes',{event:'*',schema:'public',table:'orders'},load).subscribe(); return()=>{supabase.removeChannel(ch)}},[shop])
 function recommend(){let available=wheel.filter(n=>!form.specified||n===form.specified); if(form.specified) return [form.specified]; return available.slice(0,Number(form.people))}
 async function createOrder(){const assigned=recommend(); const order={shop,phone_tail:form.phone_tail,people:Number(form.people),duration:Number(form.duration),start_time:form.start_time,status:'scheduled',assigned,base_fee:Number(form.base_fee),extra_fee:Number(form.extra_fee),tip:Number(form.tip),base_pay_method:form.base_pay_method,extra_pay_method:form.extra_pay_method,tip_pay_method:form.tip_pay_method}; await supabase.from('orders').insert(order); if(!form.specified){setWheel([...wheel.filter(n=>!assigned.includes(n)),...assigned])}; setForm({...form,phone_tail:'',start_time:nowTime()}); load()}
 const stats=useMemo(()=>{const s:Record<string,{cash:number,check:number,total:number,count:number}>={}; orders.forEach(o=>{o.assigned?.forEach(n=>{s[n]??={cash:0,check:0,total:0,count:0}; const p=calcPay(o); s[n].cash+=p.cash; s[n].check+=p.check; s[n].total+=p.total; s[n].count++})}); return s},[orders])
 return <main style={{fontFamily:'Arial',maxWidth:1050,margin:'0 auto',padding:16}}><h1>按摩店预约轮钟系统</h1><select value={shop} onChange={e=>setShop(e.target.value)}><option>Weatherford</option><option>Mineral Wells</option></select><h2>今日轮钟</h2><div>{wheel.map((n,i)=><button key={n} onClick={()=>{const w=[...wheel]; if(i>0){[w[i-1],w[i]]=[w[i],w[i-1]];setWheel(w)}}} style={{margin:4,padding:10}}>{i+1}. {n}</button>)}</div><h2>新订单</h2><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:8}}>{['phone_tail','start_time','extra_fee','tip'].map(k=><label key={k}>{k}<input value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label>人数<select value={form.people} onChange={e=>setForm({...form,people:e.target.value})}>{[1,2,3,4].map(x=><option key={x}>{x}</option>)}</select></label><label>时长<select value={form.duration} onChange={e=>setForm({...form,duration:e.target.value})}>{[30,60,75,90,120].map(x=><option key={x}>{x}</option>)}</select></label><label>大费<select value={form.base_fee} onChange={e=>setForm({...form,base_fee:e.target.value})}>{[70,90,110].map(x=><option key={x}>{x}</option>)}</select></label><label>指定<select value={form.specified} onChange={e=>setForm({...form,specified:e.target.value})}><option value=''>无指定</option>{defaultWorkers.map(n=><option key={n}>{n}</option>)}</select></label><label>大费付款<select value={form.base_pay_method} onChange={e=>setForm({...form,base_pay_method:e.target.value})}><option value='card'>刷卡</option><option value='cash'>现金</option></select></label><label>额外付款<select value={form.extra_pay_method} onChange={e=>setForm({...form,extra_pay_method:e.target.value})}><option value='cash'>现金</option><option value='card'>刷卡</option></select></label><label>小费付款<select value={form.tip_pay_method} onChange={e=>setForm({...form,tip_pay_method:e.target.value})}><option value='cash'>现金</option><option value='card'>刷卡</option></select></label></div><p>推荐：<b>{recommend().join(' + ')}</b> 结束：{addMin(form.start_time,Number(form.duration))}</p><button onClick={createOrder} style={{padding:14,fontSize:18}}>确认添加订单</button><h2>今日工资</h2><table border={1} cellPadding={8}><thead><tr><th>技师</th><th>单数</th><th>今天现金发</th><th>刷卡待支票</th><th>总收入</th></tr></thead><tbody>{Object.entries(stats).map(([n,v])=><tr key={n}><td>{n}</td><td>{v.count}</td><td>${v.cash}</td><td>${v.check}</td><td>${v.total}</td></tr>)}</tbody></table><h2>订单</h2>{orders.map(o=><div key={o.id} style={{border:'1px solid #ddd',padding:8,margin:8}}>{o.start_time} {o.people}P {o.duration}min {o.assigned?.join('+')} 电话{o.phone_tail} 现金发${calcPay(o).cash} 支票${calcPay(o).check}</div>)}</main>
}
